### ISSUE TITLE
context canceled during post

### ISSUE THREAD

**Issue by changsijay** [samber/slog-slack#3]
in my backedn API call, I tested with

```
logger.ErrorContext(ctx, "failed to get user from DB", "userID", userID)
```

and then return the API response immediately, but didnt see message in slack.

since the `postMessage` is a goroutine, if it use the context from the request.
then it probably will be cancelled if response fast.

would it better to use a new context with timeout in `postMessage`?
```
ctx = context.WithTimeout(context.Background(), h.option.Timeout)
```

**Comment by samber** [comment]
done -> v2.4.0
